import type { ModelInfo } from '../types.js';

export const ANTHROPIC_MODELS: ModelInfo[] = [
  {
    id: 'claude-sonnet-4-20250514',
    provider: 'anthropic',
    displayName: 'Claude Sonnet 4',
    pricing: { input: 3, output: 15 },
    contextWindow: 200000,
    maxOutputTokens: 64000,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
  },
  {
    id: 'claude-3-5-sonnet-20241022',
    provider: 'anthropic',
    displayName: 'Claude 3.5 Sonnet',
    pricing: { input: 3, output: 15 },
    contextWindow: 200000,
    maxOutputTokens: 8192,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    aliases: ['claude-3-5-sonnet', 'claude-3.5-sonnet'],
  },
  {
    id: 'claude-3-5-haiku-20241022',
    provider: 'anthropic',
    displayName: 'Claude 3.5 Haiku',
    pricing: { input: 0.8, output: 4 },
    contextWindow: 200000,
    maxOutputTokens: 8192,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    aliases: ['claude-3-5-haiku', 'claude-3.5-haiku'],
  },
  {
    id: 'claude-3-opus-20240229',
    provider: 'anthropic',
    displayName: 'Claude 3 Opus',
    pricing: { input: 15, output: 75 },
    contextWindow: 200000,
    maxOutputTokens: 4096,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
    },
    aliases: ['claude-3-opus'],
  },
  {
    id: 'claude-3-sonnet-20240229',
    provider: 'anthropic',
    displayName: 'Claude 3 Sonnet',
    pricing: { input: 3, output: 15 },
    contextWindow: 200000,
    maxOutputTokens: 4096,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
    },
    aliases: ['claude-3-sonnet'],
  },
  {
    id: 'claude-3-haiku-20240307',
    provider: 'anthropic',
    displayName: 'Claude 3 Haiku',
    pricing: { input: 0.25, output: 1.25 },
    contextWindow: 200000,
    maxOutputTokens: 4096,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
    },
    aliases: ['claude-3-haiku'],
  },
];

