import type { ModelInfo } from '../types';

export const ANTHROPIC_MODELS: ModelInfo[] = [
  {
    id: 'claude-opus-4-5-20251101',
    provider: 'anthropic',
    displayName: 'Claude Opus 4.5',
    pricing: { input: 5, output: 25 },
    contextWindow: 200000,
    maxOutputTokens: 64000,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    aliases: ['claude-opus-4-5', 'claude-opus-4.5'],
  },
  {
    id: 'claude-sonnet-4-5-20250929',
    provider: 'anthropic',
    displayName: 'Claude Sonnet 4.5',
    pricing: { input: 3, output: 15 },
    contextWindow: 200000,
    maxOutputTokens: 64000,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    aliases: ['claude-sonnet-4-5', 'claude-sonnet-4.5'],
  },
  {
    id: 'claude-haiku-4-5-20251001',
    provider: 'anthropic',
    displayName: 'Claude Haiku 4.5',
    pricing: { input: 1, output: 5 },
    contextWindow: 200000,
    maxOutputTokens: 64000,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    aliases: ['claude-haiku-4-5', 'claude-haiku-4.5'],
  },
  {
    id: 'claude-opus-4-1-20250805',
    provider: 'anthropic',
    displayName: 'Claude Opus 4.1',
    pricing: { input: 15, output: 75 },
    contextWindow: 200000,
    maxOutputTokens: 32000,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    aliases: ['claude-opus-4-1', 'claude-opus-4.1'],
    deprecated: true,
  },
  {
    id: 'claude-sonnet-4-20250514',
    provider: 'anthropic',
    displayName: 'Claude Sonnet 4',
    pricing: { input: 3, output: 15 },
    contextWindow: 200000,
    maxOutputTokens: 64000,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    aliases: ['claude-sonnet-4-0', 'claude-sonnet-4'],
    deprecated: true,
  },
  {
    id: 'claude-opus-4-20250514',
    provider: 'anthropic',
    displayName: 'Claude Opus 4',
    pricing: { input: 15, output: 75 },
    contextWindow: 200000,
    maxOutputTokens: 32000,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    aliases: ['claude-opus-4-0', 'claude-opus-4'],
    deprecated: true,
  },
  {
    id: 'claude-3-7-sonnet-20250219',
    provider: 'anthropic',
    displayName: 'Claude 3.7 Sonnet',
    pricing: { input: 3, output: 15 },
    contextWindow: 200000,
    maxOutputTokens: 64000,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    aliases: ['claude-3-7-sonnet', 'claude-3.7-sonnet'],
    deprecated: true,
  },
  {
    id: 'claude-3-5-sonnet-20241022',
    provider: 'anthropic',
    displayName: 'Claude 3.5 Sonnet',
    pricing: { input: 3, output: 15 },
    contextWindow: 200000,
    maxOutputTokens: 8192,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    aliases: ['claude-3-5-sonnet', 'claude-3.5-sonnet'],
    deprecated: true,
  },
  {
    id: 'claude-3-5-haiku-20241022',
    provider: 'anthropic',
    displayName: 'Claude 3.5 Haiku',
    pricing: { input: 0.8, output: 4 },
    contextWindow: 200000,
    maxOutputTokens: 8192,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    aliases: ['claude-3-5-haiku', 'claude-3.5-haiku'],
    deprecated: true,
  },
  {
    id: 'claude-3-opus-20240229',
    provider: 'anthropic',
    displayName: 'Claude 3 Opus',
    pricing: { input: 15, output: 75 },
    contextWindow: 200000,
    maxOutputTokens: 4096,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
    },
    aliases: ['claude-3-opus'],
    deprecated: true,
  },
  {
    id: 'claude-3-haiku-20240307',
    provider: 'anthropic',
    displayName: 'Claude 3 Haiku',
    pricing: { input: 0.25, output: 1.25 },
    contextWindow: 200000,
    maxOutputTokens: 4096,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
    },
    aliases: ['claude-3-haiku'],
    deprecated: true,
  },
];
