import type { ModelInfo } from '../types';

export const GOOGLE_MODELS: ModelInfo[] = [
  {
    id: 'gemini-3-pro-preview',
    provider: 'google',
    displayName: 'Gemini 3 Pro Preview',
    pricing: { input: 3, output: 15 },
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    aliases: ['gemini-3-pro'],
  },
  {
    id: 'gemini-3-flash-preview',
    provider: 'google',
    displayName: 'Gemini 3 Flash Preview',
    pricing: { input: 0.75, output: 3 },
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    aliases: ['gemini-3-flash'],
  },
  {
    id: 'gemini-2.5-pro',
    provider: 'google',
    displayName: 'Gemini 2.5 Pro',
    pricing: { input: 1.875, output: 12.5 },
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
  },
  {
    id: 'gemini-2.5-flash',
    provider: 'google',
    displayName: 'Gemini 2.5 Flash',
    pricing: { input: 0.65, output: 2.5 },
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    aliases: ['gemini-flash'],
  },
  {
    id: 'gemini-2.5-flash-lite',
    provider: 'google',
    displayName: 'Gemini 2.5 Flash Lite',
    pricing: { input: 0.2, output: 0.4 },
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    aliases: ['gemini-flash-lite'],
  },
  {
    id: 'gemini-2.0-flash',
    provider: 'google',
    displayName: 'Gemini 2.0 Flash',
    pricing: { input: 0.1, output: 0.4 },
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    aliases: ['gemini-2-flash'],
    deprecated: true,
  },
  {
    id: 'gemini-2.0-flash-lite',
    provider: 'google',
    displayName: 'Gemini 2.0 Flash Lite',
    pricing: { input: 0.075, output: 0.3 },
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    deprecated: true,
  },
  {
    id: 'gemini-1.5-pro',
    provider: 'google',
    displayName: 'Gemini 1.5 Pro',
    pricing: { input: 1.25, output: 5 },
    contextWindow: 2097152,
    maxOutputTokens: 8192,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    aliases: ['gemini-pro'],
    deprecated: true,
  },
  {
    id: 'gemini-1.5-flash',
    provider: 'google',
    displayName: 'Gemini 1.5 Flash',
    pricing: { input: 0.075, output: 0.3 },
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    deprecated: true,
  },
  {
    id: 'gemini-1.5-flash-8b',
    provider: 'google',
    displayName: 'Gemini 1.5 Flash 8B',
    pricing: { input: 0.0375, output: 0.15 },
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    deprecated: true,
  },
];
