import type { ModelInfo } from '../types.js';

export const GOOGLE_MODELS: ModelInfo[] = [
  {
    id: 'gemini-2.5-pro-preview-05-06',
    provider: 'google',
    displayName: 'Gemini 2.5 Pro',
    pricing: { input: 1.25, output: 10 },
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    aliases: ['gemini-2.5-pro'],
  },
  {
    id: 'gemini-2.5-flash-preview-05-20',
    provider: 'google',
    displayName: 'Gemini 2.5 Flash',
    pricing: { input: 0.15, output: 0.6 },
    contextWindow: 1048576,
    maxOutputTokens: 65536,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    aliases: ['gemini-2.5-flash'],
  },
  {
    id: 'gemini-2.0-flash',
    provider: 'google',
    displayName: 'Gemini 2.0 Flash',
    pricing: { input: 0.1, output: 0.4 },
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    aliases: ['gemini-2-flash'],
  },
  {
    id: 'gemini-1.5-pro',
    provider: 'google',
    displayName: 'Gemini 1.5 Pro',
    pricing: { input: 1.25, output: 5 },
    contextWindow: 2097152,
    maxOutputTokens: 8192,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    aliases: ['gemini-pro'],
  },
  {
    id: 'gemini-1.5-flash',
    provider: 'google',
    displayName: 'Gemini 1.5 Flash',
    pricing: { input: 0.075, output: 0.3 },
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
    aliases: ['gemini-flash'],
  },
  {
    id: 'gemini-1.5-flash-8b',
    provider: 'google',
    displayName: 'Gemini 1.5 Flash 8B',
    pricing: { input: 0.0375, output: 0.15 },
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    capabilities: {
      supportsTools: true,
      supportsVision: true,
      supportsFunctions: true,
      supportsStreaming: true,
      supportsJson: true,
    },
  },
];
